llm_model: "gpt-4"
tts_model: "en-us-kathleen-low.onnx"
tts_api_base: "http://api:8080"
functions_model: "functions"
api_base: "http://api:8080"
stablediffusion_api_base: "http://api:8080"
stablediffusion_model: "stablediffusion"